language: python
#python:
  #  - "2.6"
#  - "2.7"
  # - "3.2"
  # - "3.3"
#  - "3.6"
env:
    - CONDA_PYTHON_VERSION=2.7
    - CONDA_PYTHON_VERSION=3.6
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$CONDA_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
#    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#    - chmod +x miniconda.sh
#    - ./miniconda.sh -b
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # GUI
    - "export DISPLAY=:99.0"
    - sh -e /etc/init.d/xvfb start
# sudo: false
# command to install dependencies
install:
    - conda update --yes conda
    # Install dependencies

    - conda install --yes -c SimpleITK -c luispedro -c mjirik -c conda-forge --file requirements_conda.txt python=$CONDA_PYTHON_VERSION
    - pip install pygco
#    - pip install -r ci/requirements_ci.txt
      # - "easy_install SimpleITK mahotas"
#    - pip install -r requirements_pip.txt
    # - if [ ${pack} == "old_mpl" ]; then conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose dateutil pandas statsmodels pil six; fi
    - conda install -y nose
    - pip install python-coveralls
    - conda list
#    - apt-cache policy openssl
#    - conda install --yes paramiko=1.16.0

#    - 'echo "include /usr/local/lib" | sudo tee -a /etc/ld.so.conf'
#    - sudo ldconfig -v
    # get sample data for lisa
#    - python -m io3d.datasets -l lisa
    - nosetests --help

# command to run tests
script: nosetests --with-coverage --verbose -d --cover-package=pysegbase
# script: nosetests --with-coverage --verbose --nocapture --nologcapture --cover-package=lisa
# script: nosetests --with-coverage --cover-package=lisa
after_success:
    - coveralls
